language: node_js
node_js:
  - "node"
dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest-nightly
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
